logging:
  level:
    com.honey.reservationadmin: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server.port: 8081
---
spring:
  config:
    activate:
      on-profile: heroku
  sql:
    init:
      mode: always
project.reservation.url: ${PROJECT_RESERVATION_URL}
